### ISSUE TITLE
TW frontend launch

### ISSUE THREAD

**Issue by brandonhundt** [PRX/theworld.org#117]
## Ahead of Launch day
- [x] Look at Drupal production settings files for redirects  (update these redirects) (NEEDS PRI ticket) 
- [x] Test pri.org proxy using proxytest.pri.org, and confirm routing. 
- [x] theworld.org DNS is going to live at route 53 (GBH)
- [x] Make the switch over to route 53 DNS, as soon as possible, after Rick and Kai review.
- [x] Confirm Vercel plan (Andrew)
- [x] Add a develop/prod preview branch for the frontend
- [x] Set up Plausible account for theworld.org
- [x] Double check TTL
- [x] PR that rearranges fields on the TW program page edit form (make it easier to access the curated story links)
- [x] ensure `embed.pri.org` redirects/proxies/points to `embed.theworld.org`

## Launch Day
- [x] Decrease TTL to a minute
- [x] Cache Clear (include Restful) 
- [x] Drupal Backup
- [x] Drupal code deployment of new redirect settings
- [x] Run Drush Production script (this breaks theworld.org redirect in Drupal)
- [x] In Drupal, change the primary domain in the Live Drupal Config to theworld.org
- [x] Point theworld.org DNS to the Vercel site
- [x] Point PRI.org DNS to the PRX Proxy 
- [x] Cache Clear (include Restful)
- [x] Confirm proxy is working as expected (stories/feeds/etc)
- [x] Change the "Edit Homepage" link to `/node/3704/edit` [Note, I'm unable to control this view in a feature]

## After Launch
- [x] Remove TheWorld.org set up on Pantheon
- [ ] Ensure the PRX proxy can handle traffic concerns.
- [ ] Verify Google webmaster and search console tools for TW.
- [ ] Uninstall unneeded Frontend Modules on Drupal site (like Google Analytics/Chartbeat)
- [ ] Lighten Drupal story page load (remove views/CTAs/related links, etc)
- [ ] Story bio change from Field Collection to Entity group
- [ ] Preview mode for draft content pages. 
- [ ] Delete `theworld.org` DNS zone from GCP
