### ISSUE TITLE
EPIC: Refactor Data Fetchers to WP GraphQL

### ISSUE THREAD

**Issue by brandonhundt** [PRX/theworld.org#347]
According to @rpeterman-gp: Update data fetchers to point to Wordpress API. Once one thing changes everything else will cascade, so it will be tough not break everything.

```[tasklist]
### Tasks
- [ ] https://github.com/PRX/theworld.org/issues/386
- [ ] https://github.com/PRX/theworld.org/issues/389
- [ ] https://github.com/PRX/theworld.org/issues/387
- [ ] https://github.com/PRX/theworld.org/issues/388
- [ ] https://github.com/PRX/theworld.org/issues/392
- [ ] https://github.com/PRX/theworld.org/issues/396
- [ ] https://github.com/PRX/theworld.org/issues/394
- [ ] https://github.com/PRX/theworld.org/issues/398
- [ ] https://github.com/PRX/theworld.org/issues/400
- [ ] https://github.com/PRX/theworld.org/issues/402
- [ ] https://github.com/PRX/theworld.org/issues/406
- [ ] https://github.com/PRX/theworld.org/issues/403
- [ ] https://github.com/PRX/theworld.org/issues/409
- [ ] https://github.com/PRX/theworld.org/issues/405
- [ ] https://github.com/PRX/theworld.org/issues/407
- [ ] https://github.com/PRX/theworld.org/issues/418
- [ ] https://github.com/PRX/theworld.org/issues/419
- [ ] https://github.com/PRX/theworld.org/issues/417
```

**Comment by rpeterman-gp** [comment]
Wordpress data work is complete! 🎉
